### ISSUE TITLE
Some aliases no longer visible in listnodes

### ISSUE THREAD

**Issue by sumBTC** [ElementsProject/lightning#3194]
I automatically find aliases via: `lightning-cli listnodes`

Since I updated to `v0.7.3`some aliases are no longer part of `listnodes`. The IDs are there but without aliases. I suspect it happens with c-lightning versions `<= 0.7.2`. LND and Eclair aliases seem the same (see my [website]( http://Bitkoins.nl) and look for alias_unknown)

For example `ln.rene-pickhardt.de`. The node ID is in `listnodes` (I even have a channel with that node) but without the alias.

### `getinfo` output
Alias: Bitkoins.nl
Version: v0.7.3rc3"

**Comment by darosior** [comment]
> Since I updated to v0.7.3

Which version ? There has been some gossip fixups between the rcs.

**Comment by sumBTC** [comment]
Version: v0.7.3rc3 (that was written under getinfo output.) but the problem started already with rc2.

**Comment by niftynei** [comment]
missing aliases is a side-effect of your node not having node_announcement gossip messages for that node.

prior RC's of c-lightning weren't being very aggressive with pushing out their own node_announcements, see #3152

**Comment by sumBTC** [comment]
@niftynei So it's only a problem with c-lightning versions 0.7.3.rc1 and/or 0.7.3.rc2 or also with older versions of c-lightning? If only with the two rcs, I will close the issue.

**Comment by whitslack** [comment]
It was a problem in 0.7.2 too. See #2969.

I am still experiencing the issue on 0.7.3rc3. Even after my node has been running for three days on 0.7.3rc3, I am still missing node announcements for a sizable fraction of my connected peers.

**Comment by niftynei** [comment]
There are two issues to discuss here, which have the same net result— your node appears to be missing aliases for other nodes.

In the case of “my node is missing alias information from recent c-lightning nodes”, this is likely due to them not sending them very aggressively. #3152 addresses this

In the case of “Im missing large swaths of aliases from nodes, not just from clightning peers”, this is typically a result of not asking our peers for a wide enough range to net the missing information. It should be fixed in RC3 (we now look for a wide range of missing node announcements to ask our peers about). If you’re still having trouble, you can give it a kick by deleting* your gossip store, this will resync all the gossip en masse. Note that if the reason they’re missing is because the above issue, this won’t do much to help as it’s unlikely your peers have the missing information either.

*i.e. stop your node, rename the gossip store to `gossip_store.bak`, restart node

**Comment by whitslack** [comment]
@niftynei: Thanks for the clarifications. Even if I don't zap my `gossip_store`, shouldn't my node *eventually* fill in all the node announcements it's missing just due to routine gossip refreshes? How long is that expected to take?

**Comment by niftynei** [comment]
@whitslack well that depends on *why* the announcements are missing. assuming that they’re relatively well represented on other nodes, they should get picked up by the gossip seeker eventually. I’d need to check but I believe it was changed to run once every ~24hrs

**Comment by whitslack** [comment]
@niftynei: 100 of my 386 peers are showing no alias after my node has been up for 62 hours. Does this suggest that the seeker is malfunctioning?

```
$ lightning-cli listpeers | jq -r '.peers[] | .id' | xargs -d'\n' -n1 lightning-cli listnodes | jq '.nodes[] | has("alias") or has("color")' | awk '{ counts[$0]++ } END { for (value in counts) print value, counts[value] }'
false 100
true 286
```

**Comment by sumBTC** [comment]
I've updated to the latest version (v0.7.3rc3-2-g0985c6e), removed the gossip_store (like I've done before) and the problem is still there for some nodes (probably only with c-lightning nodes).

**Comment by darosior** [comment]
> probably only with c-lightning nodes

Yep, I've seen this on my node and it's indeed only C-lightning nodes. They might not have upgraded yet.

**Comment by whitslack** [comment]
> it's indeed only C-lightning nodes.

@darosior: How do you tell what software your peer is running? I'd love to instrument that, but I haven't found a way.

**Comment by darosior** [comment]
> @darosior: How do you tell what software your peer is running? I'd love to instrument that, but I haven't found a way.

Actually checking 1ML ^^

**Comment by sumBTC** [comment]
@whitslack I only know they are c-lightning nodes because I decided to only connect to c-lightning nodes a couple of months ago when I was often getting fatal errors with LND nodes (this issue has now been resolved by ignoring these error messages). I found the c-lightning nodes looking for node IDs in the issues. Nevertheless and interesting question.

**Comment by poperbu** [comment]
I updated my node from 7.2 to 7.3 and I have the same problem. only 1038 of 4615 listed nodes are not empty.

**Comment by darosior** [comment]
Hello @poperbu, it must be due to the remote side which has not updated yet

**Comment by poperbu** [comment]
ok, I understand now,...so We need to wait that all nodes update their info? It is a problem for plugins and tools that use listnodes calls, if we need to wait long time to know the alias...

**Comment by whitslack** [comment]
As much as I would love to believe that 114 of my 392 peers are running buggy C-Lightning release candidates, I think we all know that C-Lightning just isn't that popular. No, our lack of node announcements is not *solely* due to a plethora of buggy C-Lightning release candidates running in the wild. It is evident that there is still a logic error in the gossip code of C-Lightning 0.7.3.

**Comment by sumBTC** [comment]
Yep, this commit solves the issue. Thanks to all!

**Comment by rustyrussell** [comment]
OK, if you want to fix existing nodes, I've written a script to do so.  I've appended it to the Release files, along with a canned set of node_announcements for mainnet

https://github.com/ElementsProject/lightning/releases/download/v0.7.3/insert-unknown-nodes.sh
https://github.com/ElementsProject/lightning/releases/download/v0.7.3/node-announces.tar.xz
