### ISSUE TITLE
Payments very rarely work

### ISSUE THREAD

**Issue by nakoshi-satamoto** [ElementsProject/lightning#7180]
I am not sure if it is just me or others also, but I have noticed that ever since updating to version 24 most payments fail.

I get alot of these messages, the htlc and node number varies though.

`htlc 16 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)`

then payment deadline expires.

I have even attempted to pay various invoices even with small payments, I also have some large channels (millions of sats) open with large and well connected nodes.

Posting this for visibility in case if others are experiencing this also. If there is something I can check to confirm if it is an issue with my node or corelightning I can do so.

**Comment by nakoshi-satamoto** [comment]
To clarify, it is uncertain if this is a problem wiht my node or something to do with core lightning.

**Comment by vincenzopalazzo** [comment]
What happens if you put `disable-mmp` inside your config file and restart your node?

**Comment by nakoshi-satamoto** [comment]
@vincenzopalazzo  I was away from computer but I can try that now. Before I do that I want to know what that setting does. I am not finding any documentation on it. What is that setting?

**Comment by vincenzopalazzo** [comment]
the setting disable the multi path payment algorithm

**Comment by nakoshi-satamoto** [comment]
disable-mmp is not a recgonized command or config setting by my Core Lightning.

**Comment by vincenzopalazzo** [comment]
@nakoshi-satamoto is `disable-mpp` sorry

**Comment by kilrau** [comment]
> @nakoshi-satamoto is `disable-mpp` sorry

Did this change anything for you? @nakoshi-satamoto

**Comment by nakoshi-satamoto** [comment]
@kilrau I actually did not need to.

Ever since I upgraded to core lightning verison 24.02 I kept getting alot of these errors in my logs for various channels. This also was an issue on V24.02.1

`2024-04-15T04:27:36.026Z UNUSUAL lightningd: Bad gossip order: could not find channel 696011x284x1 for peer's channel update
`

After updating to the latest version of core lightning onto version 43.02.2 those gossip issues went away, transactions inbound and outbound are not failing anymore. Maybe it was related to gossip not working?

**Comment by vincenzopalazzo** [comment]
>Maybe it was related to gossip not working?

probably yes

**Comment by nakoshi-satamoto** [comment]
No longer an issue

**Comment by BitcoinMechanic** [comment]
Did 24.02.2 fix this for you? I upgraded to that and I'm still having the same issue. (Pages of `Bad gossip order....`)

**Comment by nakoshi-satamoto** [comment]
On 2024-05-05 18:52, BitcoinMechanic wrote:
> Did 24.02.2 fix this for you? I upgraded to that and I'm still having
> the same issue. (Pages of `Bad gossip order....`)

I am on 24.02.2 and I still get those bad gossip order messages. I am 
able to do payments though.

**Comment by blapcity** [comment]
also on 24.02.02 with high - payment failure rate and bad gossip order messages

**Comment by crc32** [comment]
I'm also on 24.02.02 (using the BTCPay Docker image), and 100% payment failures unless paying direct channel partners, and tons of bad gossip order messages. Cannot query remote routes at all, even to targets that are direct partners of channel partners. Incoming payments and some through-routes seem to work though (the through routes may only be working to next-node termination though).

**Comment by nakoshi-satamoto** [comment]
I said that I can still do payments, I am ammending my claim. I can receive inbound payments no problem but I do have a high rate of failure for outbound payments unless it is a direct peer. Ever since I upgraded to version 24 I have noticed this and it also coinciding with the gossip error messages. I delete gossip database and it still keeps getting gossip errors.

**Comment by TTK-199837** [comment]
I am also experiencing this exact issue.

**Comment by rustyrussell** [comment]
*DO NOT* delete the gossip store, you will not be able to make payments any more.  You've made the network disappear, and it can take a while to refill.

Are you missing gossip?  A healthy node should look like this:

```
$ lightning-cli -H listchannels | grep -c ^short_channel_id
85921
$ lightning-cli -H listnodes | grep -c ^nodeid
9062
```

That is, about 85000 public channels and 9000 nodes.

**Comment by TTK-199837** [comment]
Well… in an attempt to make my core lightning node functional again I did delete the gossip store (but did save a backup! (This was… a week ago?)) should I just continue as is or cp gossip_store.backup to replace the “new” one? Have you not noticed any payment issues Rusty?

On Mon, Jun 3, 2024, at 9:26 PM, Rusty Russell wrote:
> 
> 
> *DO NOT* delete the gossip store, you will not be able to make payments any more. You've made the network disappear, and it can take a while to refill.
> 
> Are you missing gossip? A healthy node should look like this:
> 
> `$ lightning-cli -H listchannels | grep -c ^short_channel_id
> 85921
> $ lightning-cli -H listnodes | grep -c ^nodeid
> 9062
`

**Comment by strnly** [comment]
Found this issue and could relate instantly. 

Same situation for me. BTCPay Server, CLN. 
Fat channels (7-12m sats) with major peers and payments to these peers fail 95%. 
Failed payments to Boltz, Strike, WoS despite have fat channels with them. 

Incoming payments, no problem at all. Outgoing, 95%+ failure.

**Comment by nakoshi-satamoto** [comment]
On 2024-06-04 06:26, Rusty Russell wrote:
> *DO NOT* delete the gossip store, you will not be able to make
> payments any more.  You've made the network disappear, and it can take
> a while to refill.
> 
> Are you missing gossip?  A healthy node should look like this:
> 
> ```
> $ lightning-cli -H listchannels | grep -c ^short_channel_id
> 85921
> $ lightning-cli -H listnodes | grep -c ^nodeid
> 9062
> ```
> 
> That is, about 85000 public channels and 9000 nodes.

What is wrong with deleting gossip? I have done that often times in 
version 24 to fix gossip issues. It re-populates fast.
I deleted gossip yesterday after I upgraded to version 24.05 which 
claims to fix the gossip issues.

I just checked and I have 92910 channels, 16063 nodes.

**Comment by blapcity** [comment]
Did this resolve your issue with payments ?

**Comment by nakoshi-satamoto** [comment]
On 2024-06-07 02:33, blapcity wrote:
> Did this resolve your issue with payments ?

I had the opportunity to test some payments today. I have 12 chans and 
almost 10,000,000 of outbound liquidity combined. Many of the peers I'm 
connected to are well connected also. I tried three random payments of 
less than 100,000 to different destinations and all of them failed. I 
still see gossip errors sometimes also, even after upgrading to 24.05 
and rebuliding gossip. I'd say my gossip database is healthy also as I 
have 14427 nodes, 92599 chans in my view.

As of now, Core Lightning _cannot_ send payments unless it is a directly 
connected peer. This is not functional.

**Comment by nakoshi-satamoto** [comment]
On 2024-06-10 19:46, Satoshi wrote:

> I had the opportunity to test some payments today. I have 12 chans and
> almost 10,000,000 of outbound liquidity combined.

10 millions sats.

**Comment by cdecker** [comment]
Any chance we could get some more logs to try and hone in on the cause for the increased failure rate? From the above they all seem to come more or less directly after deleting gossip_store (fails immediately due to lack of network view, rather than taking some time and performing real attempts).

The gossip order is very likely to be unrelated, so ignore that maybe for a bit. It is mostly a warning that the peer has given us gossip messages in the incorrect order (update before announcement, or node before any of it's channels).

**Comment by cdecker** [comment]
One more thing, how many here are running btcpayserver? As it has been mentioned a number of times, I'd like to exclude that as a potential source.

**Comment by cdecker** [comment]
Ok, I think I see what's happening. Just to be sure, can you provide the couple more lines above the snippet you posted? It contains the channel hints that we initialize based on our local view of the channels (`listpeerchannels`) which we then use to compute the actual route as an overlay on the gossip. It seems that we are picking a local channel that is either not fully reestablished or does not have sufficient balance. Then we somehow track the limits wrong and retry the same channel over and over again. At least skimming the logs, that's my best theory yet. More data and logs will help us pin this down and fix it.

Thanks for the logs, they are incredibly helpful 👍

**Comment by cdecker** [comment]
Also, please set your log levels to debug.

**Comment by compane** [comment]
Thank your for taking the time. I set log levels to debug and did three transactions.

1 sat --> succeeded
10 sats --> succeeded
1000 sats --> failed
I had a 128000 sats transaction in the past which succeeded as well.


[cln_debug_failed_1000sats_primal.txt](https://github.com/user-attachments/files/15899788/cln_debug_failed_1000sats_primal.txt)
[cln_debug_succeeded_10sats_phoenix.txt](https://github.com/user-attachments/files/15899789/cln_debug_succeeded_10sats_phoenix.txt)
[cln_debug_succeeded_1sat_primal.txt](https://github.com/user-attachments/files/15899790/cln_debug_succeeded_1sat_primal.txt)

**Comment by blapcity** [comment]
My friend runs an LND node and I'm his only channel. I have 25 large channels and I cannot send a payment to Strike but he can with 100% success make payments to strike despite his only channel being with me. Not sure if this is helpful but it confirms that there is an issue.

**Comment by lightningcheckout** [comment]
I recognize this issue as well. When local balance in direct channel isn't enough payments are failing. @cdecker is this the part you are looking for:

```
2024-06-22T07:10:13.415Z DEBUG   plugin-pay: cmd 34 partid 0: Received getchaininfo blockcount=848999, headercount=848999
2024-06-22T07:10:13.416Z DEBUG   plugin-pay: cmd 34 partid 0: waitblockheight reports syncheight=848999
2024-06-22T07:10:13.425Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 796747x1740x0/1: enabled true, estimated capacity 5195608458msat
2024-06-22T07:10:13.426Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 829208x14004966x61721/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.426Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 5960895x10194222x36605/1: enabled false, estimated capacity 4294967295msat
2024-06-22T07:10:13.426Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 848103x2170x1/0: enabled true, estimated capacity 0msat
2024-06-22T07:10:13.427Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 10454817x11377454x13607/0: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.427Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 819140x2281x1/1: enabled true, estimated capacity 54359915msat
2024-06-22T07:10:13.427Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 5591485x9388989x13342/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.427Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 826396x2260x0/1: enabled true, estimated capacity 1248975146msat
2024-06-22T07:10:13.428Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 4282556x1477417x5590/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.428Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 847889x1670x0/0: enabled true, estimated capacity 1581645457msat
2024-06-22T07:10:13.428Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 14226214x12490668x34238/0: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.428Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 831632x831x8/1: enabled true, estimated capacity 197645333msat
2024-06-22T07:10:13.429Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 12419924x6069763x832/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.429Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 830097x1343x0/0: enabled true, estimated capacity 3583467msat
2024-06-22T07:10:13.429Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 5448693x1437927x55335/0: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.429Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 794802x1236x1/1: enabled true, estimated capacity 56440577msat
2024-06-22T07:10:13.430Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 15232671x14304892x37732/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.437Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 836553x1098x0/1: enabled true, estimated capacity 12981990msat
2024-06-22T07:10:13.438Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 15804156x10261040x52402/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.438Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 825037x421x0/1: enabled true, estimated capacity 6291173857msat
2024-06-22T07:10:13.438Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 4909945x337710x31253/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.438Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 806422x1945x1/1: enabled true, estimated capacity 8341msat
2024-06-22T07:10:13.439Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 5015597x10726383x19215/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.439Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 846557x3093x0/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.439Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 1880118x5887875x11970/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.439Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 826544x3884x1/1: enabled true, estimated capacity 4673825msat
2024-06-22T07:10:13.440Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 15140828x5950323x21109/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.440Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 774864x1716x1/1: enabled true, estimated capacity 250150121msat
2024-06-22T07:10:13.440Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 8852482x10869402x60338/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.440Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 776826x3067x1/1: enabled true, estimated capacity 10719488msat
2024-06-22T07:10:13.441Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 8061376x5028423x11465/1: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.441Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 844759x290x1/0: enabled true, estimated capacity 59431000msat
2024-06-22T07:10:13.441Z DEBUG   plugin-pay: cmd 34 partid 0: Added a channel hint for 4959791x10771686x64007/0: enabled false, estimated capacity 0msat
2024-06-22T07:10:13.552Z DEBUG   plugin-pay: cmd 34 partid 0: After filtering routehints we're left with 0 usable hints
2024-06-22T07:10:13.553Z DEBUG   plugin-pay: cmd 34 partid 0: Not using a routehint
2024-06-22T07:10:13.553Z DEBUG   plugin-pay: cmd 34 partid 0: The destination is directly reachable including attempts without routehints
2024-06-22T07:10:13.650Z INFO    plugin-pay: cmd 34 partid 0: Initial limit on max HTLCs: 23475, Destination 035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226 has 1565 channels, assuming 15 HTLCs per channel
2024-06-22T07:10:13.650Z DEBUG   plugin-pay: cmd 34 partid 0: Created outgoing onion for route: 774864x1716x1 -> 841217x2174x0 -> 841809x2912x2 -> 830185x454x0
2024-06-22T07:10:13.653Z INFO    lightningd: Sending 241409341msat in onion to deliver 241408000msat
2024-06-22T07:10:22.444Z INFO    033d38e07e2541628214c8184cf6c562311059872363e9f538b2f45434418b5bc5-chan#4: htlc 14690 failed from 2th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
```

**Comment by cdecker** [comment]
@lightningcheckout Im assuming that there are more HTLCs failing? Individual HTLCs failing is to be expected, as we don't have the balances is the open network and so LN just tries, learns then retries new HTLCs. So one htlc going awry is not suspicious, but if we end up retrying the same channel over and over again, then that'd be something to look into.

**Comment by lightningcheckout** [comment]
Indeed, payment is failing at the timeout. Can send you the complete log later today if needed?

**Comment by cdecker** [comment]
That would be very helpful indeed.

**Comment by nakoshi-satamoto** [comment]
@cdecker 

I was travelling and am back now. I captured a state of all my channels and their balances, I set my log level to debug and attempted two seperate payments to two different destinations. All failed.  **I would consider this issue to be of the highest priority for core lightning**, because at the moment Core Lightning simply is unable to do payments unless if it is to a directly connected peer. I am unable to use my node for payments because of this. I am only keeping it running in the meantime to paitently await in hope that one day this issue may be resolved.

Attached is the state of my router and channels and balances, then the debug log, then the two payment errors that went to the standard output. I am not using BTCPay, I am using Core Lightning in command line. I am using the pay command.
(Does the debug log contain sensitive info like private keys?)

Thank you for your work to you and the rest of the devs.

[LN-state-2024-Jun-22.txt](https://github.com/user-attachments/files/15937786/LN-state-2024-Jun-22.txt)
[ln-log.txt](https://github.com/user-attachments/files/15937787/ln-log.txt)
[7778sat-payment-failed.txt](https://github.com/user-attachments/files/15937788/7778sat-payment-failed.txt)
[5000sat-payment-failed.txt](https://github.com/user-attachments/files/15937789/5000sat-payment-failed.txt)

**Comment by cdecker** [comment]
Thanks for the logs @nakoshi-satamoto :+1:
We are very aware that some users are having a bad time performing payments with CLN, and it is our top priority. Please be aware that debugging a complex piece of software is not straightforward, and the lack of progress  is not due to us not trying, but rather, there was very little actionable information to debug the issue. With the provided logs I hope we can narrow down the issue to the root cause, and hopefully we'll find a fix soon.

**Comment by cdecker** [comment]
I went and looked at the 5000sat payment, that @nakoshi-satamoto added logs for, and I reconstructed the following timeline:

Timeline for the 5000sat payment:

-   2024-06-22T17:31:48.578Z Received `pay` call
-   2024-06-22T17:31:49.309Z `partid=0` uses path `836447x1783x0 -> 824675x381x0 -> 820408x3620x0 -> 830081x1392x1` resulting in HTLC 3922
-   2024-06-22T17:31:51.902Z Received an error with `update_fail_htlc`:
    -   `0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)` (this is our peer!)
    -   The included update does not disable the channel, so likely they have insufficient funds.
    -   We correctly update our local view: `Added a channel hint for 824675x381x0/0: enabled true, estimated capacity 5000049msat`
-   2024-06-22T17:31:52.850Z `partid=1` `Created outgoing onion for route: 836447x1783x0 -> 820296x552x0 -> 847399x918x0 -> 830081x1392x1`
    -   Notice we don't use the same channel as above, correctly switching away due to the detected insufficient balance
    -   `Adding HTLC 3923 amount=5000105msat cltv=849344`
-   2024-06-22T17:32:08.548Z `partid=1` Received an error with `update_fail_htlc`:
    -   `failed from 1th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)`
    -   `Added a channel hint for 847399x918x0/1: enabled true, estimated capacity 5000049msat`
    -   Too bad, the failing channel is the one leading to the destination node
-   2024-06-22T17:32:10.308Z `partid=2` `Created outgoing onion for route: 836447x1783x0 -> 809661x1625x0 -> 809661x1622x0 -> 830081x1392x1`
    -   Also correctly avoids `847399x918x0` and `824675x381x0` which we now know have insufficient balance.
    -   `Adding HTLC 3924 amount=5000105msat cltv=849344`
    -   `Added a channel hint for 809661x1625x0/0: enabled true, estimated capacity 5000099msat`
-   2024-06-22T17:32:17.109Z `partid=3` `Created outgoing onion for route: 836447x1783x0 -> 848375x2648x0 -> 832721x2744x2 -> 830081x1392x1`
    -   `Adding HTLC 3925 amount=5000055msat cltv=849350`
    -   2024-06-22T17:32:21.647Z `htlc 3925 failed from 1th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)`
    -   `Added a channel hint for 832721x2744x2/1: enabled true, estimated capacity 5000049msat`
-   2024-06-22T17:32:21.799Z `partid 4: Created outgoing onion for route: 836447x1783x0 -> 848375x2648x0 -> 847700x1843x0 -> 830081x1392x1`
    -   `Intermediate node 039174f846626c6053ba80f5443d0db33da384f1dde135bf7080ba1eec465019c3 reported 1007 (WIRE_TEMPORARY_CHANNEL_FAILURE) at 847700x1843x0 on route 836447x1783x0 -> 848375x2648x0 -> 847700x1843x0 -> 830081x1392x1`
    -   `Added a channel hint for 847700x1843x0/1: enabled true, estimated capacity 5000049msat`
-   2024-06-22T17:32:30.095Z `partid 5: Created outgoing onion for route: 836447x1783x0 -> 848375x2725x0 -> 830185x454x0 -> 830081x1392x1`
    -   `htlc 3927 failed from 1th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)`
    -   `Added a channel hint for 830185x454x0/0: enabled true, estimated capacity 5000049msat`
-   2024-06-22T17:32:36.295Z `partid 6: Created outgoing onion for route: 836447x1783x0 -> 841648x644x0 -> 841645x3064x1 -> 830081x1392x1`
    -   `htlc 3928 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)`
    -   `Added a channel hint for 841648x644x0/0: enabled true, estimated capacity 5000049msat`
-   `partid 7: Created outgoing onion for route: 836447x1783x0 -> 769934x630x0 -> 769938x2527x1 -> 830081x1392x1`
    -   `htlc 3929 failed from 1th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)`
-   `Payment deadline expired, not retrying (partial-)payment 9ddd5d3ef6de1706e26d5f1605d53c389c837fa26430e0f39ca54c02aa621c48/7`

The payment ends up failing after the 60 second send timeout
expires. It tried a whole bunch of different paths, but never
succeeded, because all paths reported insufficient balances either in
the 1- or 2-hop neighborhood. As frustrating as it may seem, this is
how the LN protocol works, and the failure rate is due to network
weather, not the behavior of the sender.

We are working on remembering channel statuses (as in the channel
hints being added dynamically) across payments, which may reduce the
attempts required to find a working path, in case of repeated
payments, but that does not help nodes that don't perform many
payments, thus have a limited view of the network weather.

As the issues arise in the <2-hop neightborhood, I'd strongly suggest
opening new channels to peers that are better connected, and that take
better care of balancing their channels. It really looks like you got
very unlucky.

The following peers or peers-of-peers caused your payment to fail:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-left" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Reporting Node ID</th>
<th scope="col" class="org-right">Channel ID</th>
<th scope="col" class="org-left">Name</th>
<th scope="col" class="org-right">HTLC</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2</td>
<td class="org-right">824675x381x0</td>
<td class="org-left">Boltz</td>
<td class="org-right">3922</td>
</tr>


<tr>
<td class="org-left">03c82c83da9e495a5f72fcfe1671f3ed84452234b82ef6f2403f24d08d59aa8295</td>
<td class="org-right">847399x918x0</td>
<td class="org-left">Nerk</td>
<td class="org-right">3923</td>
</tr>


<tr>
<td class="org-left">026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2</td>
<td class="org-right">809661x1625x0</td>
<td class="org-left">Boltz</td>
<td class="org-right">3924</td>
</tr>


<tr>
<td class="org-left">039174f846626c6053ba80f5443d0db33da384f1dde135bf7080ba1eec465019c3</td>
<td class="org-right">832721x2744x2</td>
<td class="org-left">-</td>
<td class="org-right">3925</td>
</tr>


<tr>
<td class="org-left">039174f846626c6053ba80f5443d0db33da384f1dde135bf7080ba1eec465019c3</td>
<td class="org-right">847700x1843x0</td>
<td class="org-left">-</td>
<td class="org-right">3926</td>
</tr>


<tr>
<td class="org-left">02a98e8c590a1b5602049d6b21d8f4c8861970aa310762f42eae1b2be88372e924</td>
<td class="org-right">830185x454x0</td>
<td class="org-left">-</td>
<td class="org-right">3927</td>
</tr>


<tr>
<td class="org-left">026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2</td>
<td class="org-right">841648x644x0</td>
<td class="org-left">Boltz</td>
<td class="org-right">3928</td>
</tr>


<tr>
<td class="org-left">026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2</td>
<td class="org-right">769934x630x0</td>
<td class="org-left">Boltz</td>
<td class="org-right">3929</td>
</tr>
</tbody>
</table>

It's too bad that those no-name nodes didn't have sufficient capacity,
since they were the last hop before the destination WoS, but that's
life.

So from what I can tell, it tried really hard to deliver the payment. Some slow nodes along the routes caused the payment to only ever try 8 paths, which sadly ended up with insufficient balance errors.

**Comment by cdecker** [comment]
So there are a number of initiatives we are looking into right now, and some that could use some operator input to fine-tune them:

 - We are looking into storing, and managing channel hints across payments, so that we don't have to relearn from scratch, and try routes that are unlikely to succeed. There are a number of open questions that we need to consider:
   - [ ] For learned bandwidths, how do we discount them over time, i.e., we saw a channel have an upper bound of `X`, how do we time that value out over time? For example the channel may have rebalanced, and we can slowly expand the limit over time.
   - [ ] The same from above also applies to binary signals: if a channel or node was detected as unavailable, how do we retest it, to see if we can include them in routing attemtps again?
 - Looking for ways to surface the causes for failed payments better to users. The analysis I did in the above post is rather cumbersome to pull together manually, and we'd like to communicate failures clearly. How could we collect information and present it to allow operators to debug without having to talk to the devs? We'd like to present a summary of the above as the results of calling `pay`.

We are of course open to suggestions.

**Comment by cdecker** [comment]
And the second payment has the following routes (with the failing channel with insufficient balance underlined):


-   836447x1783x0 -> 848375x2648x0 -> <span class="underline">845231x2839x2</span> -> 845572x2470x3
-   836447x1783x0 -> 848375x2725x0 -> <span class="underline">837916x538x7</span> -> 845572x2470x3
-   836447x1783x0 -> <span class="underline">805448x3033x1</span> -> 813256x389x1 -> 835598x758x1
-   836447x1783x0 -> 792411x2154x1 -> <span class="underline">833895x1409x0</span> -> 845572x2470x6 -> 845572x2470x3
-   836447x1783x0 -> <span class="underline">785515x2213x0</span> -> 830224x829x0 -> 845572x2470x6 -> 845572x2470x3
-   836447x1783x0 -> 820296x552x0 -> <span class="underline">839394x1953x2</span> -> 806578x1678x38
-   836447x1783x0 -> <span class="underline">824675x381x0</span> -> 783276x1383x0 -> 810489x1163x0 -> 845572x2470x6 -> 845572x2470x3
-   836447x1783x0 -> 820296x552x0 -> <span class="underline">839394x1952x9</span> -> 806578x1678x38
-   `Payment deadline expired, not retrying (partial-)payment 9ddd5d3ef6de1706e26d5f1605d53c389c837fa26430e0f39ca54c02aa621c48/7`


Notice you always pick Boltz as first hop, maybe excluding that peer from being used could change success rate? It seems like Boltz is so attractive to routing that the randomization we add never ends up picking another peer to go through, but then it runs into balance issues.

**Comment by cdecker** [comment]
@lightningcheckout looking into your logs, it also appears like your node ends up failing all attempts due to insufficient balance in the 1-hop and 2-hop neighborhoods.

**Comment by nakoshi-satamoto** [comment]
Thank you very much @cdecker . You are very much appreciated. 

So as I understand, it is just that my router is in a bad state for _outbound_ liquidity, even though I have a large channel open with Boltz.

I am going to test some payments with excluding Boltz chan I have open. I cannot figure out how to exclude a channel when making payments, I did read the manuals. Does anyone know how to exclude a channel for payments?

Then I was going to get more outbound liquidity on my side, maybe by rebalancing come chans and do testing again.

**Comment by nakoshi-satamoto** [comment]
If I cannot figure out how to exclude a chan for outbound payments, I may just close my boltz channel then use that to try to rebalance some other chans.

**Comment by lightningcheckout** [comment]
Did you check: https://docs.corelightning.org/reference/lightning-pay ? The exclude syntax is given here. I also use sometime the paythrough plugin to tell CLN which channel to use for the outgoing payment.

**Comment by nakoshi-satamoto** [comment]
On 2024-06-23 18:45, lightningcheckout wrote:
> Did you check: https://docs.corelightning.org/reference/lightning-pay
> ? The exclude syntax is given here. I also use sometime the paythrough
> plugin to tell CLN which channel to use for the outgoing payment.

That is the first manual page I checked. That documentation is lacking 
the information I need to craft a working command. It returns an error 
asking for amount in msats, (shouldn't this already be included in the 
bolt11 invoice?). I am not able to figure out the proper syntax even 
when I do manually input the amount again.

So unless anyone has knowledge on how to use the exclude flag in the pay 
command, this is not a valid option for me. So my only option is to 
install  the plugin to pay through a certain channel. I will try that 
later on as a test to see if I can pay through one of my other channels 
that is not Boltz. Then I shall rebalance a chan or two to get more 
outbound liquidity on my side and try payments again.

**Comment by daywalker90** [comment]
Assuming there really is an amount in the invoice you use the command like this:
```
lightning-cli pay -k bolt11=<invoice> exclude='["564334x877x1/0", "564334x877x1/1"]'
```

**Comment by nakoshi-satamoto** [comment]
On 2024-06-24 00:31, daywalker90 wrote:
> Assuming there really is an amount in the invoice you use the command 
> like this:
> ```
> lightning-cli pay -k bolt11=<invoice> exclude='["564334x877x1/0",
> "564334x877x1/1"]'
> ```

Thank you. When excluding the Boltz chan, I did a test of three payments 
to three different destinations, small payments. Two of the three still 
failed. I closed my boltz chan and rebalanced to bring back more 
outbound liquidity across different channels. Now payments are 
successful.


So it seems that although I had high amount of outbound liquidity on my 
Boltz chan, and some outbound liquidity on other chans, perhaps my node 
was just in a bad position in terms of liquidity on the network to reach 
destinations.

**Comment by compane** [comment]
@nakoshi-satamoto Was it the LND or CLN Boltz node you were connected to?

**Comment by nakoshi-satamoto** [comment]
On 2024-06-24 09:35, compane wrote:
> @nakoshi-satamoto Was it the LND or CLN Boltz node you were connected 
> to?

pubkey 
026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2

So this is Boltz, not Boltz|CLN. I am using CLN

**Comment by nakoshi-satamoto** [comment]
On 2024-06-24 15:51, Satoshi wrote:
> On 2024-06-24 09:35, compane wrote:
>> @nakoshi-satamoto Was it the LND or CLN Boltz node you were connected 
>> to?
> 
> pubkey 
> 026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2
> 
> So this is Boltz, not Boltz|CLN. I am using CLN

I mean, i am using CLN as in Core Lightning as my router. I was not 
connected to Boltz|CLN

**Comment by carboncls** [comment]
I can also report this issue is occurring to me. I can't enable debug right now, but what I can say is:

- started with versions 24.xx+
- fairly good peers, liquid channels
- disable-mpp does nothing
- going for retry_for=900 does not help
- excluding Blotz|CLN does not help
- payment size does not matter, they all fail
- I refuse to believe payments were working one day, then next day, after upgrading, the weather drastically changed

I'm wondering if devs could try to recreate the issue on testnet. Payment destination should not be a direct channel partner.

**Comment by carboncls** [comment]
Oh, and I also sometimes get this:

`{
   "code": 204,
   "message": "failed: WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS (reply from remote)",
   "id": 22561,
   "failcode": 16399,
   "failcodename": "WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS",
   "bolt11": "xxx",
   "raw_message": "400f0000000000054437000cf628",
   "created_at": 1719326903,
   "destination": "xyz",
   "payment_hash": "xxx",
   "status": "failed",
   "amount_msat": 50000000,
   "amount_sent_msat": 0,
   "erring_index": 5,
   "erring_node": "xyz"
}
`

**Comment by lightningcheckout** [comment]
Today I had another failure. 3hours later I did a retry. The first time it timed out after testing 2 routes. The second time, it had 8 routes tried, before the payment timed out. 

Two things that I wonder: 
1. The first two routes were exactly the same on the first and second attempt.
2. On both payments CLN picked 1 specific channel for the first hop: LQwD-Canada

Is that both what to expect @cdecker 

Few hours later I did retry again, the direct channel had enough balance at that moment and the payment went well.

**Comment by cdecker** [comment]
Thanks for adding more context @lightningcheckout. That is indeed rather normal behavior for an LN node trying to send a payment.

 - The first payment got unlucky, likely hit a deadend close to the destination, removing an edge that was crucial to reach the destination. That will get you only 2 attempts. It is usually also exacerbated by slow routing nodes on the attempt. They mean we only learn about a failed htlc very slowly, so we can start the next attempt only much later and we then run into the 60 second overall timeout. So nothing too surprising here, and nothing that would be fixed by remembering prior attempts since it is the first one.
 - The second payment trying the same two paths first is not surprising. We don't remember the prior inferred results, and so we try to decide based on an identical initial view of the network, thus it is rather likely that we take similar decisions.
 - The fact that a later payment succeeded also speaks for this being network weather. You didn't change anything on your end, yet the outcome is different, so it must've been the network rebalancing, nodes recovering, etc

The interesting case is the second payment: given that it reattempts a previous payment, we could expect that remembering prior attempts would help us here. However, if we were to pick for example `mpay` constraint attenuation of forgetting after 0.5h, then we would have forgotten that data again at the 3h mark when you retried. This is the difficult part of parameterizing the network view: how do we make it useful, for large nodes where there is a lot of information and it is relatively up to date, but also for small nodes which may only be doing a payment every couple of hours.

Remembering too much also means we are skipping things that used to be bad last time, but would be perfectly fine now. It's a double-edged sword if I've ever seen one 😅

**Comment by lightningcheckout** [comment]
hehe, yeah I understand the issue :-D

Today again some failed payments. Based on the more detailed view in this issue over the last weeks I can't conclude otherwise then it's bad luck in the network. Because first few payments went well, but the channels used didn't have enough liquidity for the next payment. Then CLN chooses another first hop and payments starts failing.

It keeps failing in additional attempts because CLN is choosing the exact same first hop. So storing data of failed first hops for x period would definitely improve the success ratio of payments. 

But it's really depending of the node and usage what would be a suitable time to store the failed first hops. But what about a configurable option @cdecker , and let this choice of duration by the node operator?

And how is this handled in renepay?

**Comment by cdecker** [comment]
I'm afraid noticing that we get to our peer, but then nowhere from there will not mark the peer as bad. As such we'd still continue to iterate through their channels, never penalizing the peer whose channels are bad. We could introduce a peer score, but then we'd have to come up with a sensible way of determining that based on our observations 🤔

**Comment by compane** [comment]
So I opened a second channel to a different node and all payment attempts finished successfully. Did not need do exclude the Boltz node.

**Comment by daywalker90** [comment]
Before any pay starts i would give nodes a higher cost to go through if they have 80+% of channels set to very low fees (<=10ppm) and default htlc_max set. Then during a pay i would increase the cost of using a node each time they fail.

**Comment by cdecker** [comment]
I wonder if low fees is a.good signal here, given that likely operators that want to attract traffic will set fees competitively, i.e., lowish as compared to their surroundings.

I'm tempted to have a multiplicative factor that we apply to all channels and nodes up to the failing channel, thus deprioritizing nodes and channels if they lead us into this kind of trap (nodes you can reach but not forward through). We just need to make sure with @renepickhardt's that we're not destroying our scoring function by adding things willy nilly.

**Comment by urza** [comment]
> even though I have a large channel open with Boltz.

Boltz node has a rather specific rebalancing strategy. Their customers are sending LN payments in, so they try to be ready for it and have enough liquidity on the other side. Meaning their channels are not balanced. In your case you try to route via them but I image most of they channels would fail your attempted path because they don't keep the liquidity on their side (which is what you would need). 

You should try to open big channel with some routing node that is trying to keep channels more balanced for general routing.

**Comment by naturallaw777** [comment]
Yes, I am having the same issue. Using Core Lightning v24.05. 95% of all payment fail.

I have nicely balanced channels and CLN is well connected to well connected nodes.

**Comment by nakoshi-satamoto** [comment]
On 2024-07-24 22:35, SovranSystems.com wrote:
> Yes, I am having the same issue. Using Core Lightning v24.05. 95% of
> all payment fail.
> 
> I have nicely balanced channels and CLN is well connected to well
> connected nodes.

Ever since I closed my channel with Boltz my node is able to do payments 
just fine since then. I am not saying it is Boltz fault, just that it is 
believed based on other comments in here that my node was selecting that 
as the first hop for payments causing those payments to fail. I did not 
know how to exclude a specific single channel for routing so I closed 
that channel. Again, not putting any blame on boltz. I am curious if 
others who have failing payments keep selecting the same first hop that 
has an imbalanced liquidity, and if closing that channel or excluding 
that as the 1st hop resolves.

**Comment by naturallaw777** [comment]
> On 2024-07-24 22:35, SovranSystems.com wrote: Yes, I am having the same issue. Using Core Lightning v24.05. 95% of all payment fail. I have nicely balanced channels and CLN is well connected to well connected nodes.
> Ever since I closed my channel with Boltz my node is able to do payments just fine since then. I am not saying it is Boltz fault, just that it is believed based on other comments in here that my node was selecting that as the first hop for payments causing those payments to fail. I did not know how to exclude a specific single channel for routing so I closed that channel. Again, not putting any blame on boltz. I am curious if others who have failing payments keep selecting the same first hop that has an imbalanced liquidity, and if closing that channel or excluding that as the 1st hop resolves.

I had boltz too as a channel. I did close it as per this thread. However, I am still getting failures. 

I have channels open with:

1. ACINQ
2. OLYMPUS by Zeus
3. LNServerFocus
4. LNBIG [Edge-1]
5. 1Mil.com node ALPHA

**Comment by blapcity** [comment]
>  I have 25 large channels and I cannot send a payment to Strike but he can with 100% success make payments to strike despite his only channel being with me. 

While you may have luck closing a channel and getting a payment to go through, there is still an underlying issue with how routes are selected. As a user who depends on lightning to live, the ability to make payments is what I value most.

**Comment by TTK-199837** [comment]
clightning is broken for sending. Paying is fine. I would also note that I have 1 friend that only has 1 channel - me - and he runs LND. He can ALWAYS make payments to whoever it seems. When I try to do the same amount to the same channel, they ALWAYS fail. Very frustrating.

**Comment by nakoshi-satamoto** [comment]
I still have issues. I have alot of outbound capacity and multiple channels. NO payments work for me. I cannot even do payments as small as 7,000 sats.

This all started with verison 24. Core Lightning is absolutely fundamentally broken and incapable of sending payments. Yet this issue has not been fixed or seems to be ignore. I am going to probably shutdown my node and all my channels and switch to a different software for using lightning. Which is sad, because CLN used to be the best and I would rather stick with CLN if possible because it is not programmed in golang like LND is (I have security concerns with golang), and I am familiar with CLN, I thought about just sticking with version 23 but then I risk this issue again by updating to a new version later on.

How does anyone even use Core Lightning version 24?

**Comment by nakoshi-satamoto** [comment]
Does anyone know of any alternative lightning implementations that is not LND?

**Comment by naturallaw777** [comment]
Once I closed Boltz, I am now able to send more successfully with CLN. At the same time, with LND (as I run both), it almost never fails. 

So, yes, I still think your are right about something is wrong with update 24.

**Comment by nakoshi-satamoto** [comment]
On 2024-07-30 05:28, SovranSystems.com wrote:
> Once I closed Boltz, I am now able to send more successfully with CLN.
> At the same time, with LND (as I run both), it almost never fails.
> 
> So, yes, I still think your are right about something is wrong with 
> update 24.

although I do not have a chan opn with boltz,nthese issues have come up 
for me again today. All payments were failing. I tried payments to 
different destinations and some wvwn were small payments. Yet they all 
failed.

**Comment by nakoshi-satamoto** [comment]
My last post had typos that i presume led to confustion. i know it is 
not an issue on Boltz's end. What i mean was that even without any 
channel with Boltz all my payments are still failing again. If the pay 
command is the issue, is there any alternative way to pay bolt11 
invoices?

**Comment by lightningcheckout** [comment]
> My last post had typos that i presume led to confustion. i know it is not an issue on Boltz's end. What i mean was that even without any channel with Boltz all my payments are still failing again. If the pay command is the issue, is there any alternative way to pay bolt11 invoices?

Did you check which routes are failing? Is it always the same first hop that is used? Did you try to exclude this channel in your payment? 

@cdecker is it somehow possible to exclude certain channels by default via an env variabele? For my use case that could be helpful, since I know which channels are most likely to fail.

**Comment by nakoshi-satamoto** [comment]
> Did you check which routes are failing? Is it always the same first hop that is used? Did you try to exclude this channel in your payment?

I can do some tests. How am I supposed to see what route a payment is trying to take?

**Comment by DonOregano** [comment]
So I am being bitten by this as well on my new setup. I have four well-funded channels to large nodes. But I have not dug into how their channel liquidity looks. But I tried excluding first one and then the second of my peers in a lightning pay, and then it succeeded.

**Comment by DonOregano** [comment]
> I can do some tests. How do I see what route a payment is trying to take?

I saw peer ids in my system logs, and then I excluded them with the command line option, like:
`lightning-cli pay bolt11=<invoice> exclude=["<66 char id>","<66 char id>"]`

**Comment by nakoshi-satamoto** [comment]
On 2024-08-07 14:07, Lars Hagström wrote:
>> I can do some tests. How do I see what route a payment is trying to 
>> take?
> 
> I saw peer ids in my system logs, and then I excluded them with the
> command line option, like:
> `lightning-cli pay bolt11=<invoice> exclude=["<66 char id>","<66 char 
> id>"]`

Thank you. So the issue does seem to be that when payment fails, it is 
due to a certain channel that Core Lightning is attempting, and the 
issue is that it does not re-attempt over other channels. So a work 
around indeed may be to when a payment fails, refer to the log to 
identify which channel it was failing to send over, then re-attempt 
payment again with excluding that channel that is failing the payment. 
And of course to alternatively also upload debug logs to help devs 
investigate the issue.

So we now know a work around,
A simple fix may be to just have the pay command attempt payment over 
more than just one channel in the meantime until the root cause of the 
issue is addressed.

**Comment by lightningcheckout** [comment]
A solution is already be worked on: 
https://github.com/ElementsProject/lightning/pull/7487

**Comment by nakoshi-satamoto** [comment]
I wanted to confirm a work-around that others have mentioned.

If a payment fails I look at the log to see what channel the pay plugin was attempting to send it through, I then exclude that channel on my next payment attempt and it goes through fine.

**Comment by nakoshi-satamoto** [comment]
Now even when I exclude channels payments are failing, regardless of payment size. I cannot even simply do a little 8,000 sat payment. Excluding one or more channels does nothing to resolve this. 

And this is not fixed in the next release, because the next release, v24.08rc2 does not even start up.  https://github.com/ElementsProject/lightning/issues/7595

As of now, Version 24 does not work and there is no work around. The only solution at this point is to close all channels in Core Lightning and switch to something else, or wiat for a future release that might fix this issue. v24.08rc2 does not work at the moment.

**Comment by nakoshi-satamoto** [comment]
I think I am closing down my Core Lightning node sadly, now I have to re-program things to work with a different lightning implementation. This goes back to my question, what other options are there? Is LND the only option? I'd rather avoid go-lang if possible.

**Comment by nakoshi-satamoto** [comment]
> > Does anyone know of any alternative lightning implementations that is not LND?
> 
> None that I can recommend. We at Boltz are set on CLN and determined to get this fixed, there is nothing that comes close with regards to stability and flexibility.

@kilrau How can you say that "nothing comes close" when CLN does not even support payments? Isn't the ability to do payments the main purpose of the lightning network? I really am curious how you are even getting CLN to work if you are using CLN. I have a well established node but I am closing all my channels tonight to switch to something else (LND is maybe the only option at this point, as much as I hate go-lang) or I am going to fork CLN from versoin 23.

**Comment by kilrau** [comment]
> > > Does anyone know of any alternative lightning implementations that is not LND?
> > 
> > 
> > None that I can recommend. We at Boltz are set on CLN and determined to get this fixed, there is nothing that comes close with regards to stability and flexibility.
> 
> @kilrau How can you say that "nothing comes close" when CLN does not even support payments? Isn't the ability to do payments the main purpose of the lightning network? I really am curious how you are even getting CLN to work if you are using CLN. I have a well established node but I am closing all my channels tonight to switch to something else (LND is maybe the only option at this point, as much as I hate go-lang) or I am going to fork CLN from versoin 23.

Well we were as frustrated as you were so @michael1011 wrote [`mpay`](https://github.com/BoltzExchange/boltz-backend/tree/master/tools/plugins/mpay) - our very own pay plugin which works mostly just fine for us. It's very simple, e.g. doesn't support mpp (probably also the reason why it mostly works). It's *not* battle tested and because it's python a bit of a pain to setup but after reading through this issue you might just be motivated enough to give it a shot. [Others are happy with it](https://github.com/ElementsProject/lightning/issues/6793#issuecomment-2150995644). See some installation gotchas [here](https://github.com/BoltzExchange/boltz-backend/issues/547).

**Comment by aquilafedele** [comment]
I confirm I am getting the same problems with the impossibility to pay any invoice which does not end on my direct peers.
I have two channels only, one with Phoenix.

I was able to pay an invoice today by using Renepay and excluding one of the two channels.

Since the payment was completed, I expect it should be doable automatically from a QR scan, without the need to manually exclude a channel.

I am available to provide any details needed to figure out a solution, or to make some tests like paying myself on WoS. Let me know.

**Comment by musdom** [comment]
I am facing this issue as well when trying to pay to destinations I don't have a direct channel with. renepay works though

**Comment by buildalight** [comment]
I am creating a bounty to fix this problem.

Funding at 1AzajWfrD8X6XoJEZ2Vshbd5492B1sxamT.
https://bitcoinexplorer.org/address/1AzajWfrD8X6XoJEZ2Vshbd5492B1sxamT
 
Core Lightning's problem: the pay function fails (https://github.com/ElementsProject/lightning/issues/7180).
 
Boltz Exchange wrote a workaround plugin (https://github.com/ElementsProject/lightning/issues/6793) but this fix is insufficient. CLN needs a native pay function that works out-of-the box. LND and Phoenix fail to find payment routes at times, but not like CLN, which constantly fails to pay invoices, regardless of the number of nodes connected, channel balance, or invoice amount.
 
Once CLN is fixed and deployed (i.e. once users can use the native pay function reliably without any add-ons/plugins), the funds in the address above will be sent to the developers who are responsible for the fix. If multiple developers contribute to the solution, the funds will be allocated proportionally, with CLN lead developer Rusty Russell determining the payout proportions.
 
For updates to this bounty, see: https://pastebin.com/raw/iACc2pYv

To verify fund ownership: `bitcoin-cli verifymessage "1AzajWfrD8X6XoJEZ2Vshbd5492B1sxamT" "IAm8YePM6nkiwGbUFiIkR2mztqS6lNNlvv16jvmH3W9adpYTg5CBZAL5ImeEc6NOdyeTVu2e9eyduyzg1j96fN0=" "Fix Core Lightning and Win This Bitcoin!"`

**Comment by TheCodermasterr** [comment]
> I am creating a bounty to fix this problem.
> 
> Funding at 1AzajWfrD8X6XoJEZ2Vshbd5492B1sxamT. https://bitcoinexplorer.org/address/1AzajWfrD8X6XoJEZ2Vshbd5492B1sxamT
> 
> Core Lightning's problem: the pay function fails (#7180).
> 
> Boltz Exchange wrote a workaround plugin (#6793) but this fix is insufficient. CLN needs a native pay function that works out-of-the box. LND and Phoenix fail to find payment routes at times, but not like CLN, which constantly fails to pay invoices, regardless of the number of nodes connected, channel balance, or invoice amount.
> 
> Once CLN is fixed and deployed (i.e. once users can use the native pay function reliably without any add-ons/plugins), the funds in the address above will be sent to the developers who are responsible for the fix. If multiple developers contribute to the solution, the funds will be allocated proportionally, with CLN lead developer Rusty Russell determining the payout proportions.
> 
> For updates to this bounty, see: https://pastebin.com/raw/iACc2pYv
> 
> To verify fund ownership: `bitcoin-cli verifymessage "1AzajWfrD8X6XoJEZ2Vshbd5492B1sxamT" "IAm8YePM6nkiwGbUFiIkR2mztqS6lNNlvv16jvmH3W9adpYTg5CBZAL5ImeEc6NOdyeTVu2e9eyduyzg1j96fN0=" "Fix Core Lightning and Win This Bitcoin!"`

enjoy, libplugin-pay.c , Addr: 174139836282ferT1B4ULchkLqvCFujyNM.

[https://pastebin.com/xJXX6i12](https://pastebin.com/xJXX6i12)

**Comment by buildalight** [comment]
> enjoy, libplugin-pay.c , Addr: 174139836282ferT1B4ULchkLqvCFujyNM.
> https://pastebin.com/xJXX6i12
I can't read this code, but if this is the solution, get the CLN developers to incorporate your solution into Core Lightning's codebase to fix CLN's native _pay_ function.  Once you have achieved this, please let us know and we'll download the latest CLN package to verify that the _pay_ function has been fixed, and pay you whatever proportion of the allocated funds Rusty Russell specifies.

**Comment by aquilafedele** [comment]
In case anyone is working on this problem from the Core Lightning team, I will be in Lugano for Plan B Forum.
Feel free to get in touch with me if you like to make some tests using my node.

**Comment by nakoshi-satamoto** [comment]
I have not been using lightning since I hvae closed all my channels a couple months ago. I am curious, is this still an issue even with version 24.08, people who report as still having issues with payments (that are not destined for directly connected peers) are you using the latest most up to date version? I happened to see there was another version in the last 20 hours from the time of thist post, 24.08.2. Thank you everyone and to all the developers.

**Comment by paulscode** [comment]
It is still an issue as of 24.08.1 (latest version currently on StartOS).  I'll post an update once 24.08.2 has been pulled in.

**Comment by lightningcheckout** [comment]
I just updated my node, so perhaps I can most likely give some more insights in the upcoming days. 
@cdecker , should we already see better payment results in 24.8.2?

**Comment by Silarous** [comment]
I'm experiencing the same issue with CLN on my RaspiBlitz.  I'm getting 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE) when trying to pay anyone.  I upgraded to v24.08.2 to see if it would resolve it but unfortunately, it didn't.  I have an option in the RaspiBlitz to view a CLN node summary and when I select that, it shows num_channels=4, num_connected=4, and num_gossipers=0.  It appears that the node isn't gossiping with channel partners at all for some reason?  I would assume num_gossipers should be equal to the amount of channels or peers.

I also had to delete the gossip store to get CLN to start when it became corrupted from a hard shutdown about a month ago.  Perhaps that could have caused this issue?

**Comment by kilrau** [comment]
Let me reply on behalf of the CLN team as they don't seem to be monitoring this issue: they are 100% aware of `pay` being borked and @rustyrussell is working on an entirely new version of pay with top prio since quite some time. It's called `xpay` and he attempts to get it into the next release ([sauce](https://primal.net/e/note1jenf7cw5097st3uzhtr6xe97uhc8pnypmwyxh43hncw6um8cdtxqhjtq7u)).

So the answer to this thread is: `xpay` fixes this, we hopefully can all get our hands on it to give it its first real world testing with the next CLN release

**Comment by cdecker** [comment]
So in v24.08.2 we started remembering information across payments, so you'll see a boost if you send multiple payments in a short timeframe (so that the inferred information isn't stale and can be used). xpay for sure is going to improve this massively.

**Comment by Lagrang3** [comment]
As we speak, there is a working version of renepay that people could try.
I use it myself by default and had no issues paying merchants at Lugano.

For users using a remote control app, or not able to call renepay directly, you could
run this plugin that *replaces* pay with renepay automatically
https://github.com/Lagrang3/default-renepay

**Comment by ethmik** [comment]
I just did some testing with renepay from cli and had some success. Thanks for the tip @Lagrang3

**Comment by kilrau** [comment]
Look what just dropped: https://github.com/ElementsProject/lightning/pull/7799

PS: In our limited real-world test `v24.08.2`'s `pay` indeed seems quite a bit better :pray: @cdecker

**Comment by whitslack** [comment]
If `xpay` is a payment plugin based on `askrene`, then how does it differ from `renepay`, and how should users choose between the two seemingly duplicative payment plugins?

I've been using `renepay` quite a bit because it seems to have better success rates than `pay`, but it also crashes all the time too. Thankfully, it is not marked as a critical plugin and so doesn't take down my whole node when it crashes, and I can just start it back up again, though I do wonder if any payment attempts that it had in progress will be properly cleaned up in that case. I haven't noticed a spike in channels unilaterally closing due to HTLC deadlines, so I suppose it must be okay.

**Comment by cdecker** [comment]
You touched directly on the reason there: renepay is a standalone reimplementation of pay, combining both the planning as well as the execution of a payment. These two, interleaved, steps are rather complex on their own, and reimplementing them the execution side was lacking, hence the crashes.

With askrene and xpay, Rusty has taken a step back and noticed that the planning and execution phase do not have to be as tightly coupled. Xpay now implements the execution of the payments, while askrene contains the planning phase. The advantage is that we can tweak and experiment with the planning in askrene, or replace it wholesale, without having to reimplement the execution logic, which was the cause for renepay's lack of stability.

TL;DR: renepay is being split apart into xpay and askrene, because it frees us from having to reimplement the execution logic for every experiment.

**Comment by urza** [comment]
> Is there an eta for the new release that includes xpay? Renepay only works for me when I pay bolt11 invoices. It doesn’t work when I pay bolt12 or some LNURL addresses.
> 
> Additionally, pay doesn’t work at all for me, hence me using renepay in the meantime.

Hello, if you want to pay to LNURL or bolt12 from commandline using CLN, you can use my interactive cmd tool `payto` :

https://github.com/urza/payto

**Comment by sixtysecrun** [comment]
Just in case anyone is struggling with this: as of version 24.11.1 I had to add the following:
```
xpay-handle-pay=true
```
in order to payments be handled by `xpay` plugin that is mentioned in the previous comments.
It solved the problems with `WIRE_TEMPORARY_CHANNEL_FAILURE`

**Comment by buildalight** [comment]
Rusty and the CLN team have made good progress on making payments more reliable in the last few months. `pay` and the new function `xpay` are routing payments much better than in October. CLN is on track, good work!

Rusty, to claim the bounty, post a list of bitcoin addresses with the proportion of the 2 BTC bounty you want sent to each address.

**Comment by sangbida** [comment]
This issue is being closed as part of issue cleanup.

**Reason**: About deprecated feature

If you believe this issue should remain open, please comment and we can reopen it.
